swagger: '2.0'
info:
  title: Bank Argent API - Transactions Phase 2
  description: API endpoints for viewing and updating user transactions
  version: '2.2.0'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: List transactions by account and month
      description: Returns all transactions for the current month, grouped by account.
      parameters:
        - in: query
          name: month
          type: string
          format: date
          required: false
          description: Month to filter in YYYY-MM format (defaults to current month)
      responses:
        '200':
          description: List of transactions successfully retrieved
          schema:
            type: array
            items:
              $ref: '#/definitions/TransactionGroup'
        '401':
          description: Unauthorized - Invalid or missing token
        '500':
          description: Internal server error

  /user/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Get transaction details
      description: Retrieves detailed information about a specific transaction.
      parameters:
        - in: path
          name: transactionId
          type: string
          required: true
          description: ID of the transaction to retrieve
      responses:
        '200':
          description: Transaction details
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Transaction not found
        '500':
          description: Internal server error

    put:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Update transaction information
      description: Allows updating the transaction type, category, or adding notes to an existing transaction.
      parameters:
        - in: path
          name: transactionId
          type: string
          required: true
        - in: body
          name: body
          description: Fields to update
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      responses:
        '200':
          description: Transaction updated
        '400':
          description: Invalid data
        '404':
          description: Transaction not found

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
      accountId:
        type: string
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
        format: float
      balance:
        type: number
        format: float
      transactionType:
        type: string
        enum: [credit, debit]
      category:
        type: string
      notes:
        type: string

  TransactionUpdate:
    type: object
    properties:
      transactionType:
        type: string
        enum: [credit, debit]
      category:
        type: string
      notes:
        type: string

  TransactionGroup:
    type: object
    properties:
      accountId:
        type: string
      transactions:
        type: array
        items:
          $ref: '#/definitions/Transaction'
